apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-postgres-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iviiviagi/crossplane.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
