apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.demo.org
spec:
  group: demo.org
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    replicas:
                      type: integer
                      default: 1
